---
title: "HW3"
author: "Nick Kim"
format: html
---

Link to my [github](https://github.com/nick-kimm/HW3) repository 

## Problem 1

#Part a: 
Reading Data Files 
```{r}
library(haven)

v_file <- "/Users/nicholaskim/Documents/STAT 506/HW3/VIX_D.XPT"
vision <- read_xpt(v_file)

d_file <- "/Users/nicholaskim/Documents/STAT 506/HW3/DEMO_D.XPT"
demo <- read_xpt(d_file)
```

Merging into one dataframe:
```{r}
data<-merge(vision,demo)
#Checking if its a data frame
print(is.data.frame(data))
#Showing it reduced the size of the dataframe to only that matched
print(c(nrow(demo),nrow(data)))
```

#Part b:
Proportion of respondents in each 10 year bands. From the DEMO doc we know all possible range of values is 0-84 yrs
```{r}
#remove all rows where there is no age recorded:
data<-data[is.na(data$RIDAGEMN)!=TRUE,]

#this will store the proportion of individuals in each 10 year band into one vector
ages <- vector(length=9)

for (i in 1:9){
  ages[i] <- (nrow(data[((data$RIDAGEMN/12)<(i*10)&(data$RIDAGEMN/12)>((i-1)*10)),])/nrow(data))*100
}
```

```{r}
library(knitr)
library(kableExtra)

prop<-data.frame(t(ages))
colnames(prop)<-c("0-9","10-19","20-29","30-39","40-49","50-59","60-69","70-79","80-89")

prop%>%
  kbl(caption = "Percentage of Respondents Who Wear Glasses/Contacts in 10 yr Bands")%>%
  kable_paper()%>%
  add_header_above(c("Ages"=9))
```

#Part c:
Fitting logisitc regression models
```{r}

```


Defining a helper function
```{r}
#' db function
#'This function will shorten the function name we will call when using dbConnect for ease of use for the user
#' @param connection 
#' @param query 
#'
#' @return output from dbConnect function
gg <- function(connection,query){
  dbGetQuery(connection,query)
}
```